project:
  type: website
  output-dir: ../docs

website:
  title: "Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com


lang: pt

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

editor: visual

