project:
  type: website
  output-dir: ../docs

website:
  title: "Blog de Histórias"
  navbar:
    right:
      - Sobre.qmd
      - icon: github
        href: https://github.com/thiagoysyuki
      - icon: instagram
        href: https://www.instagram.com/resolvedortech/
      - icon: linkedin
        href: https://www.linkedin.com/in/thiagoyuki/


lang: pt

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

editor: visual

